### ISSUE TITLE
HandBrake engine crash

### ISSUE THREAD

**Issue by sdugoten** [RandomEngy/VidCoder#859] opened 2021-07-14 13:38 UTC
Basically, when I use Vidcoder to encode the video below, the encoding window disappear and the log said handbrake engine crash.    However, I can successfully encode this video without issue in Handbrake.  Please note that this is not the only video I encounter this issue.  I pick this video as an example because it happen to be smaller in size which easier to download.   I use the following encoding setting in vidcoder

![encodesetting](https://user-images.githubusercontent.com/7108552/125631195-23343783-9951-426a-ac1b-5c9a7b18091f.jpg)

Here is the log

[2021-07-14 14.25.52 Encode HD.Club-4KH265-Chimei-inn-60mbps.mp4-failed.txt](https://github.com/RandomEngy/VidCoder/files/6816414/2021-07-14.14.25.52.Encode.HD.Club-4KH265-Chimei-inn-60mbps.mp4-failed.txt)

I have another video also have similar error like this one.
[2021-07-14 14.24.18 Encode ABC.mp4-failed.txt](https://github.com/RandomEngy/VidCoder/files/6816460/2021-07-14.14.24.18.Encode.ABC.mp4-failed.txt)

Video can be download here
[https://drive.google.com/file/d/1xpzzo6_FjPjzZmT9y-jNGZtRhP7rv5nX/view?usp=sharing](url)

**Comment by sdugoten** [comment] 2021-07-14 13:42
![20210714_144151](https://user-images.githubusercontent.com/7108552/125632252-91e75ef6-5bee-418b-b97b-4aa37b45557e.jpg)

It seems like the "Align A/V start" is the cause of the  issue

**Comment by RandomEngy** [comment] 2021-07-23 05:34
Glad you found the cause. If you can reproduce the crash with HandBrake you can report it to them.

**Comment by sdugoten** [comment] 2021-07-24 20:15
> Glad you found the cause. If you can reproduce the crash with HandBrake you can report it to them.

No, the problem is that Handbrake do NOT have this problem using the option "Align A/V start".  The problem only happen on Vidcoder

**Comment by RandomEngy** [comment] 2021-08-14 17:03
I can reproduce it. Should be fixed in the next version when I update the HandBrake engine version.

**Comment by RandomEngy** [comment] 2021-09-06 03:34
Should be fixed in 6.36 Beta.

**Closed by RandomEngy** 2021-09-06 03:34 UTC
