### ISSUE TITLE
Incorrect container in Picker

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#52] opened 2016-02-18 02:11 UTC
I have a preset with the container set to mkv. Picker selects the preset but not the container, so if it was mp4 in another picker profile that's what it stays set as.

**Comment by RandomEngy** [comment] 2016-02-20 02:25
Hmm. Can't seem to reproduce the error. Could you send me your %appdata%\VidCoder-Beta\VidCoder.sqlite file and tell me the exact repro steps?

**Comment by iamjaydear** [comment] 2016-02-20 07:09
Github uploads don't work for me even when zipped, always get a stoopid failure message. Anyway, the sqlite file is at http://s000.tinyupload.com/?file_id=48711855499957046745. I'll try to document steps asap. It seems to be intermittent - Yay :(

**Comment by iamjaydear** [comment] 2016-02-21 01:38
Okay, I've been playing with this. I have various combinations of settings, destinations and containers set up in the picker. It's not actually intermittent, the only thing that seems to change when I change picker profiles is the destination - **if** it's different.  Nothing else changes as I select different picker profiles. It doesn't matter what profile (including 'none') is left selected when closing VC, thus the default next time VC is started. The settings don't change at all. Maybe this should be combined with Issue #53.

**Comment by RandomEngy** [comment] 2016-02-21 03:21
Hmm, still not able to reproduce this. What exactly are you doing? Switching which picker is selected? I can see it change between MKV and MP4 when I change from BD-MKV and TV, both from the main window and the Picker window.

**Comment by iamjaydear** [comment] 2016-02-21 03:43
I don't open the picker window, don't see the need unless I'm making a new one or editing one. I just use the drop-down arrow to the right of the picker button and select one from the drop-down list.

**Comment by iamjaydear** [comment] 2016-02-21 05:09
I've quickly installed a screen recorder and made a demo for you. Apologies for lack of audio (couldn't get it sorted quickly) and the annoying cursor movements. At least you'll see what I'm seeing. It's at http://s000.tinyupload.com/?del_id=46239857594306654400

**Comment by RandomEngy** [comment] 2016-02-21 15:48
Ahh I see what you mean. Everything seems to work if you keep the Picker window open, but things don't change over if you have it closed.

**Comment by RandomEngy** [comment] 2016-02-22 16:15
Fixed in 2.25 Beta.

**Closed by RandomEngy** 2016-02-22 16:15 UTC

**Comment by iamjaydear** [comment] 2016-02-22 18:53
Many thanks!
