### ISSUE TITLE
Suggestion for portable version of BETA:  Look and if .NET 5.0 not installed, install it by default, same look and feel as the full version

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#785] opened 2021-03-12 15:03 UTC
Look and if .NET 5.0 not installed, install it by default, same look and feel as the full version

  -- Note if .NET 5.0 is not install, the application doesn't SCAN and ENCODE at all.

**Comment by jg-github** [comment] 2021-03-12 20:26
I've been using the portable version of Vidcoder for years on my Win 7 Pro SP-1 x64 machine. I always download it from the videohelp.com website. 

I was happy to see that 6.27 beta was available, and I even read a bit and - in doing so - discovered the info about the change to NET Framework 5.0. I knew I only have NET 4.8 on my machine, but I somehow figured it would work.

I set up 6.27, but - as quebecman wrote - "if .NET 5.0 is not install, the application doesn't SCAN and ENCODE at all."

Actually, I'm not sure what he means by "SCAN": I was able to bring in my vid file and choose my settings, but when I clicked "Encode", the program froze, and the only thing I was able to do was use the program Process Explorer to kill it.

quebecman also wrote, "if .NET 5.0 not installed, install it, same look and feel as the full version".

I certainly looked, and I saw that, as I've written, my machine showed that I only have NET 4.8 installed. 

So, I dumped 6.27 beta, used the installer, everything worked as expected. This obviously meant NET 5.0 was installed. As as additional test, I then ran Windows Update, and lo and behold, M$ updated whatever version of NET 5.0  Vidcoder had installed to v. 5.0.4! And this is a Win 7 machine on which I've been using the "ESU Bypass" to do updates!

I then uninstalled Vidcoder beta and set up the portable again. Since NET 5.0.4 was now on my machine, it worked fine.

So why have I written all this? Basically, to corroborate what quebecman has said. Somehow users need to be informed that they have to have NET 5.0. 

You might say "it's obvious", but it wasn't to me. 

Anyway, thanks for your great work David. Vidcoder's definitely a winner!

**Comment by quebecman** [comment] 2021-03-12 20:36
If you try to select a complete folder of many video files, it will display, SCANNING and it will get stuck there.  But if you add manually, one by one the files, it works.

Thanx. Regards.

**Comment by jg-github** [comment] 2021-03-12 20:46
Thank you quebecman. Now I understand what you meant.

Of course it's also possible to download .NET 5.0 from the M$ site:https://dotnet.microsoft.com/download/dotnet/5.0 

I guess you should use this one as of today (12 Mar 2021) -> .NET Desktop Runtime 5.0.4. The page says, "The .NET Desktop Runtime enables you to run existing Windows desktop applications. This release includes the .NET Runtime, you do not need to install it separately."

Anyway, the important thing is that 6.27 portable beta users need to understand that NET 5.0 has to be installed before the program will work.

I'm not sure, though, if making the portable beta automatically install it is the way to go. I mean, "portable" - in my understanding - means that nothing is installed.  

Anyway, I'm sure a good solution will be found.

Have a nice weekend.

**Comment by RandomEngy** [comment] 2021-03-13 01:35
It's supposed to work without the .NET Runtime installed at all. I published it in "self-contained" mode for that purpose, and tested it on a virtual machine without .NET Runtime installed. I'll give it another look though.

**Comment by jg-github** [comment] 2021-03-13 17:42
body p { margin-bottom: 00; margin-top: 0pt; } 


Hi David,

I hope you're well. This is Joe Greenman, your "partner" in the (Pale
Moon) Rehost Image effort.

I've just re-tested the portable version of 6.27 beta on both Win 7 and
Win 10 (x64), and I've confirmed - at least on my machines - that if
NET Framework 5+ (I have  5.0.4) isn't installed on the computer, as
far as I was able to tell, the portable version of 6.27 beta doesn't
encode. I didn't check the multiple-file scan problem that quebecman
alluded to. 

The program simply freezes, and I had to use Process Explorer to
terminate it on both OS versions.

My Win10 machine is an Intel NUC8i3BEH; it has NET 4.3 x64. The two
Win7 machines are Lenovo S20s; both have NET 4.8 x64. I'll be happy to
provide more hardware info if you'd like.

On the Win 7 machines, my solution was to use the Vidcoder 6.27 beta
installer, which triggered the installation of NET 5. When I got the
portable set up, I removed the installed version; since 5.04 was still
on the machine, the portable kept working fine.

On Win10, I downloaded NET 5.0.4 from MS and installed it manually.

If you'd like me to try anything else, just let me know.

Have a nice weekend.

--

**Comment by LittleDudeNZ** [comment] 2021-03-13 21:25
On my Win10 machine portable does not run also without NET 5. It just sits there and I have to "kill it" with task manager.

**Comment by RandomEngy** [comment] 2021-03-13 22:10
Should be fixed in 6.28 Beta. The Portable version should run and encode without any need for the .NET Runtime.

**Closed by RandomEngy** 2021-03-13 22:10 UTC

**Comment by LittleDudeNZ** [comment] 2021-03-14 00:46
6.28 portable now working on my system 👍
