### ISSUE TITLE
7.10 Installer is FUBAR!

### ISSUE THREAD

**Issue by Neipas09** [RandomEngy/VidCoder#979] opened 2022-02-13 23:17 UTC
### Problem Description

Unable to install and run Vidcoder with 7.10 installer .exe
Tried downloading .exe and using chocolatey. Fails no matter what.

### What version of VidCoder are you running?

7.10

**Comment by RandomEngy** [comment] 2022-02-13 23:18
What version of Windows are you using? What happens exactly when you try to run the installer? Do you see any window open at all?

**Comment by Neipas09** [comment] 2022-02-13 23:28
I'm using Windows 10.
[image: image.png]

The vidcoder splash screen pops up.
It says installing with a progress bar.
[image: image.png]

The bar seems to go all the way to the end.
But there's nothing after that.
No icon on the desktop. Nothing is found when i search for vidcoder to run
it.

**Comment by starkebn** [comment] 2022-02-14 00:00
same issue here. Fully updated Windows 10. The installer runs, then the program wont start - nothing in task manager either. Completely uninstalled and removed registry traces doesn't change the issue.

**Comment by RandomEngy** [comment] 2022-02-14 00:01
When you go to `%localappdata%\VidCoder.Stable` do you see files there? It should look something like this:

![image](https://user-images.githubusercontent.com/9450861/153781221-f6b769ad-af1f-4989-8044-d1a38331dd4e.png)

Trying to figure out how far the installer got.

**Comment by starkebn** [comment] 2022-02-14 00:05
I had previously used an uninstall tool to clean everything away, so there was nothing there. Just ran the installer again and while it still doesn't load, this is in the directory

![image](https://user-images.githubusercontent.com/36748864/153781394-022d8169-d5cc-4cca-bbb0-822463b86979.png)

**Comment by RandomEngy** [comment] 2022-02-14 00:10
Okay can you open a command prompt/powershell/windows terminal to the VidCoder.Stable directory and try these commands?

```
Update.exe --squirrel-install 7.10.0
Update.exe --squirrel-firstrun
```

Let me know if any shortcuts get created when running it manually, or if anything shows up in the command line output.

https://github.com/clowd/Clowd.Squirrel/blob/develop/docs/using/debugging-installs.md

**Comment by RandomEngy** [comment] 2022-02-14 00:11
Oh also check `%appdata%\VidCoder\Logs%` for an `Install.txt` (that should be near the bottom of the list)

**Comment by starkebn** [comment] 2022-02-14 00:31
are you sure that syntax is correct? It just prints out the help and I have to control-C to get a command line back.

````
C:\Users\Brendan\AppData\Local\VidCoder.Stable>Update.exe --squirrel-firstrun

C:\Users\Brendan\AppData\Local\VidCoder.Stable>
Squirrel Updater (2.7.98-pre+88e1cc) manages packages and installs updates for Squirrel
applications
Usage: Update.exe command [OPTS]

Commands:
      --uninstall                 Uninstall the app in the same directory as Update.exe
      --download=VALUE            Download the releases specified by the URL and write
                                    new results to stdout as JSON
      --checkForUpdate=VALUE      Check for one available update and writes new results
                                    to stdout as JSON
      --update=VALUE              Update the application to the latest remote version
                                    specified by URL
      --createShortcut=VALUE      Create a shortcut for the given executable name
      --removeShortcut=VALUE      Remove a shortcut for the given executable name
      --updateSelf=VALUE          Copy the currently executing Update.exe into the
                                    default location

Options:
  -h, -?, --help                  Display Help and exit
  -i, --icon=VALUE                Path to an ICO file that will be used for icon shortcuts
  -l, --shortcut-locations=VALUE  Comma-separated string of shortcut locations, e.g. '
                                    Desktop,StartMenu'
      --updateOnly                Update shortcuts that already exist, rather than
                                    creating new ones
```

`

**Comment by starkebn** [comment] 2022-02-14 00:32
and there's no folder in \roaming for vidcoder at all, so no log file

**Comment by RandomEngy** [comment] 2022-02-14 02:51
Okay that's good to know as well. That means that it never ran the "on install" actions for VidCoder. It got hung up in some earlier step.

As for the command line, I actually had not tried it. But I did find another place to look for logs: `%localappdata%\SquirrelClowdTemp` . There should be a Squirrel.log file in there.

**Comment by Milincho** [comment] 2022-02-14 14:08
Same here.  But it is not just the installation. Downloaded the .zip and extracted it to a folder. Ran it and vicoder.exe shows up in task manager...    and unloads without stating any error. Very "stable".

**Comment by starkebn** [comment] 2022-02-14 21:39
here's my log if it helps

[Squirrel.log](https://github.com/RandomEngy/VidCoder/files/8064159/Squirrel.log)

**Comment by RandomEngy** [comment] 2022-02-15 03:12
Thanks for the logs. This doesn't reproduce for me when I run the .exe or when I run via command line via `Vidcoder.exe --squirrel-install 7.10.0`, so all the help is appreciated.

Here is my code to run on install:

	public static void HandleSquirrelEvents()
	{
		SquirrelAwareApp.HandleEvents(onInitialInstall: OnInitialInstall, onAppUninstall: OnAppUninstall);
	}

	private static void OnInitialInstall(SemanticVersion version, IAppTools tools)
	{
		var logger = new SetupLogger("Install");
		logger.Log("Running initial install actions...");

		try
		{
			using var mgr = new UpdateManager(Utilities.SquirrelUpdateUrl);
			mgr.CreateUninstallerRegistryEntry();
			mgr.CreateShortcutForThisExe(ShortcutLocation.StartMenu | ShortcutLocation.Desktop);

			CopyIconFilesToRoot(logger);

			RunElevatedSetup(install: true, logger);
			logger.Log("Initial install actions complete.");
		}
		catch (Exception exception)
		{
			logger.Log(exception.ToString());
			throw;
		}
		finally
		{
			logger.Close();
		}
	}

It sounds like the uninstaller registry entries were created successfully, but from @starkebn 's screenshot, the icons didn't get copied to the root folder. So if this is hanging, it must be hanging on the `mgr.CreateShortcutForThisExe(ShortcutLocation.StartMenu | ShortcutLocation.Desktop);` call.

@caesay did you see anything in `%appdata%\VidCoder\Logs` folder after you ran it? It should have at least created that folder, as that's part of the `SetupLogger` constructor.

**Comment by caesay** [comment] 2022-02-15 08:27
@RandomEngy The log folder is not created. Running the program with or without arguments fails to create the logs folder (I checked roaming and local appdata), nor does it show any window. I suspected the process is failing to start due to a missing dependency or hanging somewhere before the Squirrel hooks even run. 

Looking at event viewer after trying to launch VidCoder.exe, there are several errors - but the one of primary interest is probably this:

```txt
Application: VidCoder.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

Notably, the reference is looking for 6.0.2 and I only have 6.0.1 installed. My impression was that these .net patches were incremental and compatible, so I wouldn't expect an error like this. 

Installing the x64 desktop runtime 6.0.2 manually solved the error and VidCoder.exe was able to start.

The current Squirrel logic when checking for installed runtimes will accept _any_ version of 6.0.* as valid when installing. I suppose the logic could be to always install the latest dotnet runtime if the currently installed version is not the latest, but that feels less than optimal. Thoughts?

**Comment by Milincho** [comment] 2022-02-15 09:23
Same here, after manually installing the x64 desktop runtime 6.0.2 now version 7.10 works.

**Comment by RandomEngy** [comment] 2022-02-15 18:56
Good catch! I'd be fine with specifying a specific version to target. That would negate the need to embed more tools in the installer to go snooping around DLLs.

**Comment by starkebn** [comment] 2022-02-15 21:53
7.11 is loadnig fine

**Comment by Neipas09** [comment] 2022-02-15 22:27
Installing 7.11.exe doesn't work when trying to update from version 6.46

**Comment by RandomEngy** [comment] 2022-02-15 23:00
@Neipas09 When you say "doesn't work", what are you seeing? Is it getting stuck? Closing? Do you see an error message? Did you try manually installing the .NET x64 Desktop Runtime 6.0.2?

**Comment by caesay** [comment] 2022-02-16 01:02
After installing .net 6.0.2 I was able to install 6.46, follow the update prompts and get upgraded to 7.10 (and then subsequently 7.11 right afterwards). The old application got cleaned up successfully and the new version was launched. Presumably for anyone _without_ 6.0.2, the old version of vidcoder will not be removed properly. 

I'm working on something for Squirrel to allow a min dotnet version to be specified when building your installer, I should be able to publish an update for this tomorrow or the day after.

**Comment by Neipas09** [comment] 2022-02-16 03:36
> @Neipas09 When you say "doesn't work", what are you seeing? Is it getting stuck? Closing? Do you see an error message? Did you try manually installing the .NET x64 Desktop Runtime 6.0.2?

I did install .NET 6.0.2
![image](https://user-images.githubusercontent.com/58871039/154191236-202efd41-4d63-4d18-9397-3537cb12c22d.png)

I tried installing 7.11 after that, and it puts files into `%localappdata%\VidCoder.Stable`
![image](https://user-images.githubusercontent.com/58871039/154191438-eae2eb30-91ac-4407-ae2d-dbf5e5ecb1ab.png)

But when i try to run the Vidcoder.exe nothing opens.

**Comment by Neipas09** [comment] 2022-02-16 03:57
> After installing .net 6.0.2 I was able to install 6.46, follow the update prompts and get upgraded to 7.10 (and then subsequently 7.11 right afterwards). The old application got cleaned up successfully and the new version was launched. Presumably for anyone _without_ 6.0.2, the old version of vidcoder will not be removed properly.

I tried this, and could never get 7.10 to run.
It keeps running v6.46 and saying there's an update for 7.10 no matter how many times i tell it to update.

**Comment by RandomEngy** [comment] 2022-02-16 06:24
You need to instant the .NET 6.0.2 *Desktop* Runtime.

**Comment by Neipas09** [comment] 2022-02-16 14:44
> You need to instant the .NET 6.0.2 _Desktop_ Runtime.

ooooh.... :-/
if this specific version of .NET is soooo important, then why isn't the vidcoder installer installing it?

**Comment by RandomEngy** [comment] 2022-02-16 15:21
caesay is in this thread and works on the installer framework that VidCoder is switching to. It's supposed to install the appropriate version of the .NET framework automatically but currently there is an issue where it doesn't work in all circumstances. He's working on a fix in the next few days and I'll pick it up for VidCoder after it's ready.

**Closed** 2022-02-19 06:30 UTC
Labels: bug

**Comment by caesay** [comment] 2022-03-05 20:11
@RandomEngy Just wanted to add, it turns out this is actually a bug in the 6.0.200 SDK (rather than the issue with the approach we had in Squirrel). 

Can see here https://github.com/dotnet/wpf/issues/6109 and https://github.com/dotnet/winforms/issues/6663.

I think I will keep the changes made to Squirrel, because I believe they were good changes to have anyway (adding a warning to detect this when it happens, and allowing more specificity when selecting a dotnet runtime)... However, in the future, when this issue with the SDK is resolved (or by employing the workaround mentioned at one of those links) you can revert back to just using `--framework net6` and your app will work just fine.

**Comment by RandomEngy** [comment] 2022-03-09 07:18
Thanks for the update. I'll change back to net6-x64 when they fix the issue.
