### ISSUE TITLE
Vidcoder x64 v2.27.0.0 Beta Cropping bug!

### ISSUE THREAD

**Issue by kairukun93** [RandomEngy/VidCoder#79] opened 2016-04-20 18:22 UTC
Ok, i wanted to encode the movie "Jumper" from Blu-ray disc backup, everything encodes fine, except that when i finish encoding the movie, I expect to have the resolution of 1920x800 for Anamorphic Widescreen, the issue is that it's stuck with 1080p not cropped to 800p after encoding, so why is this happening? I'm reporting this problem if anyone have the same issue, please report away! thank you!

**Comment by RandomEngy** [comment] 2016-04-20 19:27
Yeah, Handbrake updated their filter format, so all filters (including rescale/crop) are messed up. Working on a fix.

**Comment by RandomEngy** [comment] 2016-04-20 19:28
Duplicate of https://github.com/RandomEngy/VidCoder/issues/73

**Closed by RandomEngy** 2016-04-20 19:28 UTC
