### ISSUE TITLE
Vidcoder Error Mesage

### ISSUE THREAD

**Issue by cdoruff** [RandomEngy/VidCoder#914] opened 2021-11-03 23:27 UTC
VidCoder 6.42 Installer
System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.RegularExpressions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Text.RegularExpressions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at VidCoder.FileCleanup.CleanHandBrakeTempFiles()
   at VidCoder.ViewModel.MainViewModel.OnClosing()
   at VidCoder.Services.Windows.WindowManager.OnClosing(Window window, Boolean userInitiated)
   at VidCoder.Services.Windows.WindowManager.OnClosingHandler(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by valkryie999** [comment] 2021-11-07 06:47
Report Intel QSV Error

# VidCoder 6.42
# Starting job 1/1
#   Source path: E:\[SubsPlease] 86 - Eighty Six - 16 (1080p) [51DD10DB].mkv
#   Destination path: F:\[SubsPlease] 86 - Eighty Six - 16 (1080p) [51DD10DB].mkv
#   Title: 1
#   Range: All
#   Preset: Custom Preset
# Worker ready: Pipe 'VidCoderWorker.999e4232-d457-4d86-81bb-950fcfbee155' is open
# Connecting to process 1464 on pipe VidCoderWorker.999e4232-d457-4d86-81bb-950fcfbee155
[13:44:00] CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
[13:44:00]  - logical processor count: 16
[13:44:00] Intel Quick Sync Video support: yes, gpu list: 1
[13:44:00] Intel Quick Sync Video integrated adapter with index 1
[13:44:00]  - Intel Media SDK hardware: API 1.34 (minimum: 1.3)
[13:44:00]  - Decode support:  h264 hevc (8bit: yes, 10bit: yes) av1 (8bit: yes, 10bit: yes)
[13:44:00]  - H.264 encoder: yes
[13:44:00]     - preferred implementation: hardware (2) via D3D11
[13:44:00]     - capabilities (hardware):  breftype icq+la+i+downs vsinfo opt1 opt2+mbbrc+extbrc+trellis+ib_adapt+nmpslice
[13:44:00]  - H.265 encoder: yes (8bit: yes, 10bit: yes)
[13:44:00]     - preferred implementation: hardware (2) via D3D11
[13:44:00]     - capabilities (hardware):  lowpower bpyramid icq vsinfo opt1
[13:44:00] hb_scan: path=E:\[SubsPlease] 86 - Eighty Six - 16 (1080p) [51DD10DB].mkv, title_index=1
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:333: failed opening UDF image E:\[SubsPlease] 86 - Eighty Six - 16 (1080p) [51DD10DB].mkv
src/libbluray/disc/disc.c:437: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:437: error opening file BDMV\BACKUP\index.bdmv
src/libbluray/bluray.c:2646: nav_get_title_list(E:\[SubsPlease] 86 - Eighty Six - 16 (1080p) [51DD10DB].mkv\) failed
[13:44:00] bd: not a bd - trying as a stream/file instead
libdvdread: DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdnav: vm: vm: failed to read VIDEO_TS.IFO
[13:44:00] dvd: not a dvd - trying as a stream/file instead
Input #0, matroska,webm, from 'E:\[SubsPlease] 86 - Eighty Six - 16 (1080p) [51DD10DB].mkv':
  Metadata:
    encoder         : no_variable_data
    creation_time   : 1970-01-01T00:00:00.000000Z
  Duration: 00:23:40.11, start: 0.000000, bitrate: 8122 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS-eng         : 7960053
      DURATION-eng    : 00:23:40.045000000
      NUMBER_OF_FRAMES-eng: 34047
      NUMBER_OF_BYTES-eng: 1412954293
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(jpn): Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      BPS-eng         : 128000
      DURATION-eng    : 00:23:40.109000000
      NUMBER_OF_FRAMES-eng: 61159
      NUMBER_OF_BYTES-eng: 22721748
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: ass (default)
    Metadata:
      title           : English subs
      BPS-eng         : 85
      DURATION-eng    : 00:23:28.460000000
      NUMBER_OF_FRAMES-eng: 251
      NUMBER_OF_BYTES-eng: 14986
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3: Attachment: ttf
    Metadata:
      filename        : Roboto-Medium.ttf
      mimetype        : application/x-truetype-font
  Stream #0:4: Attachment: ttf
    Metadata:
      filename        : Roboto-MediumItalic.ttf
      mimetype        : application/x-truetype-font
  Stream #0:5: Attachment: ttf
    Metadata:
      filename        : arial.ttf
      mimetype        : application/x-truetype-font
  Stream #0:6: Attachment: ttf
    Metadata:
      filename        : arialbd.ttf
      mimetype        : application/x-truetype-font
  Stream #0:7: Attachment: ttf
    Metadata:
      filename        : comic.ttf
      mimetype        : application/x-truetype-font
  Stream #0:8: Attachment: ttf
    Metadata:
      filename        : comicbd.ttf
      mimetype        : application/x-truetype-font
  Stream #0:9: Attachment: ttf
    Metadata:
      filename        : times.ttf
      mimetype        : application/x-truetype-font
  Stream #0:10: Attachment: ttf
    Metadata:
      filename        : timesbd.ttf
      mimetype        : application/x-truetype-font
  Stream #0:11: Attachment: ttf
    Metadata:
      filename        : trebuc.ttf
      mimetype        : application/x-truetype-font
  Stream #0:12: Attachment: ttf
    Metadata:
      filename        : trebucbd.ttf
      mimetype        : application/x-truetype-font
  Stream #0:13: Attachment: ttf
    Metadata:
      filename        : verdana.ttf
      mimetype        : application/x-truetype-font
  Stream #0:14: Attachment: ttf
    Metadata:
      filename        : verdanab.ttf
      mimetype        : application/x-truetype-font
[13:44:01] scan: decoding previews for title 1
[13:44:01] scan: audio 0x1: aac, rate=44100Hz, bitrate=1 ??? (AAC LC) (2.0 ch)
[13:44:01] scan: 10 previews, 1920x1080, 23.976 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1, color profile: 1-1-1
[13:44:01] scan: supported video decoders: avcodec qsv
[13:44:01] libhb: scan thread found 1 valid title(s)
[13:44:01] Starting work at: Sun Nov 07 13:44:01 2021
[13:44:01] 1 job(s) to process
[13:44:01] json job:
{
  "Audio": {
    "AudioList": [
      {
        "Bitrate": 128,
        "DRC": 0,
        "Encoder": "av_aac",
        "Gain": 0,
        "Mixdown": 4,
        "NormalizeMixLevel": false,
        "Samplerate": 0,
        "Track": 0,
        "DitherMethod": 0
      }
    ],
    "CopyMask": [
      "copy:aac",
      "copy:ac3",
      "copy:eac3",
      "copy:truehd",
      "copy:dts",
      "copy:dtshd",
      "copy:mp2",
      "copy:mp3",
      "copy:flac"
    ]
  },
  "Destination": {
    "ChapterList": [
      {
        "Name": "Chapter 1"
      }
    ],
    "ChapterMarkers": true,
    "AlignAVStart": false,
    "File": "F:\\[SubsPlease] 86 - Eighty Six - 16 (1080p) [51DD10DB].part.mkv",
    "Mp4Options": {
      "IpodAtom": false,
      "Mp4Optimize": false
    },
    "Mux": "av_mkv"
  },
  "Filters": {
    "FilterList": [
      {
        "ID": 6,
        "Settings": {
          "mode": "1"
        }
      },
      {
        "ID": 13,
        "Settings": {
          "crop-bottom": "0",
          "crop-left": "0",
          "crop-right": "0",
          "crop-top": "0",
          "height": "1080",
          "width": "1920"
        }
      }
    ]
  },
  "PAR": {
    "Num": 1,
    "Den": 1
  },
  "Metadata": {},
  "SequenceID": 0,
  "Source": {
    "Angle": 1,
    "Range": {
      "Type": "chapter",
      "Start": 1,
      "End": 1
    },
    "Title": 1,
    "Path": "E:\\[SubsPlease] 86 - Eighty Six - 16 (1080p) [51DD10DB].mkv"
  },
  "Subtitle": {
    "Search": {
      "Burn": true,
      "Default": false,
      "Enable": true,
      "Forced": true
    },
    "SubtitleList": [
      {
        "Burn": false,
        "Default": false,
        "Forced": false,
        "ID": 1,
        "Offset": 0,
        "Track": 0,
        "Name": "English subs"
      }
    ]
  },
  "Video": {
    "Encoder": "qsv_h265_10bit",
    "Level": "auto",
    "Bitrate": 2500,
    "TwoPass": false,
    "Turbo": false,
    "ColorMatrixCode": 0,
    "Options": "",
    "Preset": "quality",
    "Profile": "auto",
    "QSV": {
      "Decode": false
    }
  }
}
[13:44:01] Skipping subtitle scan.  No suitable subtitle tracks.
[13:44:01] Starting Task: Encoding Pass
[13:44:01] Skipping crop/scale filter
[13:44:01] work: track 1, dithering not supported by codec
[13:44:01] work: only 1 chapter, disabling chapter markers
[13:44:01] job configuration:
[13:44:01]  * source
[13:44:01]    + E:\[SubsPlease] 86 - Eighty Six - 16 (1080p) [51DD10DB].mkv
[13:44:01]    + title 1, chapter(s) 1 to 1
[13:44:01]    + container: matroska,webm
[13:44:01]    + data rate: 8122 kbps
[13:44:01]  * destination
[13:44:01]    + F:\[SubsPlease] 86 - Eighty Six - 16 (1080p) [51DD10DB].part.mkv
[13:44:01]    + container: Matroska (libavformat)
[13:44:01]  * video track
[13:44:01]    + decoder: h264 8-bit (yuv420p)
[13:44:01]    + filter
[13:44:01]      + Framerate Shaper (mode=1)
[13:44:01]        + frame rate: 23.976 fps -> constant 23.976 fps
[13:44:01]    + Output geometry
[13:44:01]      + storage dimensions: 1920 x 1080
[13:44:01]      + pixel aspect ratio: 1 : 1
[13:44:01]      + display dimensions: 1920 x 1080
[13:44:01]    + encoder: H.265 10-bit (Intel Media SDK)
[13:44:01]      + preset:  quality
[13:44:01]      + profile: auto
[13:44:01]      + level:   auto
[13:44:01]      + bitrate: 2500 kbps, pass: 0
[13:44:01]      + color profile: 1-1-1
[13:44:01]  * subtitle track 1, English [SSA] (track 0, id 0x2, Text) -> Passthrough
[13:44:01]    + name: English subs
[13:44:01]  * audio track 1
[13:44:01]    + decoder: ??? (AAC LC) (2.0 ch) (track 1, id 0x1)
[13:44:01]      + samplerate: 44100 Hz
[13:44:01]    + mixdown: Stereo
[13:44:01]    + encoder: AAC (libavcodec)
[13:44:01]      + bitrate: 128 kbps, samplerate: 44100 Hz
[13:44:01] sync: expecting 34048 video frames
[13:44:01] qsv: integrated qsv adapter with index 1 has been selected
[13:44:01] encqsvInit: using encode-only (LowPower) path
[13:44:01] encqsvInit: H.265/HEVC Main 10 profile @ level 4.0
[13:44:01] encqsvInit: TargetUsage 4 AsyncDepth 6
[13:44:01] encqsvInit: GopRefDist 3 GopPicSize 24 NumRefFrame 3
[13:44:01] encqsvInit: BFramesMax 2 BRefType off
[13:44:01] encqsvInit: RateControlMethod VBR TargetKbps 2500 MaxKbps 2500 BufferSizeInKB 625 InitialDelayInKB 312 BRCParamMultiplier 1
[13:44:02] sync: first pts video is 0
[13:44:02] sync: "Chapter 1" (1) at frame 1 time 0
[13:44:02] sync: first pts audio 0x1 is 0
[13:44:02] qsv_enc_init: using 'hardware (2) via D3D11' implementation, API: 1.34
Error code -17,	hb_qsv_wait_on_sync	607
encqsv: hb_qsv_wait_on_sync failed (-17)
encqsvWork: qsv_enc_work failed -17
[13:44:03] work: average encoding speed for job is 0.000000 fps
[13:44:03] vfr: 68 frames output, 0 dropped and 0 duped for CFR/PFR
[13:44:03] vfr: lost time: 0 (0 frames)
[13:44:03] vfr: gained time: 0 (0 frames) (0 not accounted for)
[13:44:03] aac-decoder done: 217 frames, 0 decoder errors
[13:44:03] h264-decoder done: 112 frames, 0 decoder errors
[13:44:03] sync: got 72 frames, 34048 expected
[13:44:03] sync: framerate min 23.976 fps, max 23.976 fps, avg 23.976 fps
[13:44:03] mux: track 0, 3 frames, 65996 bytes, 175.81 kbps, fifo 8
[13:44:03] mux: track 1, 128 frames, 41938 bytes, 111.72 kbps, fifo 256
[13:44:03] mux: track 2, 0 frames, 0 bytes, 0.00 kbps, fifo 8
[13:44:04] Finished work at: Sun Nov 07 13:44:04 2021
[13:44:04] libhb: work result = 4
ERROR: Encode failed with code ErrorUnknown
# Job completed (Elapsed Time: 4s)

**Comment by RandomEngy** [comment] 2021-11-08 06:55
Duplicate of #903

**Closed by RandomEngy** 2021-11-08 06:55 UTC
