### ISSUE TITLE
DVD analysis error

### ISSUE THREAD

**Issue by albesp77** [RandomEngy/VidCoder#256] opened 2017-10-18 07:42 UTC
I've a DVD (without protection) that give me error on first analysis, so i can't convert anything, exist a more detail log to show error ? Standard log does not show anything!

**Comment by RandomEngy** [comment] 2017-10-18 16:13
Try it with HandBrake. VidCoder uses HandBrake for the core encoding engine, so if the issue reproduces there it's an issue with their code and you can ask them for help. If it doesn't reproduce with HandBrake, we know it's a VidCoder issue.

**Comment by albesp77** [comment] 2017-10-19 13:06
Handbrake works with this DVD!

**Comment by RandomEngy** [comment] 2017-10-19 17:51
Nothing in the log? What DVD is it?

**Comment by albesp77** [comment] 2017-10-23 08:00
Both software show errors in log, but Vidcoder refuse to process disc, instead Heartbrake consent to process, here both logs!

[Logs.zip](https://github.com/RandomEngy/VidCoder/files/1406173/Logs.zip)

**Comment by RandomEngy** [comment] 2017-11-23 05:14
Hmm, the logs look identical. Both had libdvdnav errors processing titles 14 and 15. What do you mean by "refuse to process"? Does it load the list of titles in the UI? Does it not allow you to add to the queue? What happens when you try to encode? Can you give a screenshot of where it gets stuck?

**Comment by albesp77** [comment] 2017-11-23 08:21
No, vidcoder does not load titles in UI, so i'm unable to convert anything, instead handbrake show titles and convert all of them!

**Comment by RandomEngy** [comment] 2017-11-23 15:28
Does it show that there was an error while scanning? Is there an empty title list? What are you seeing?

**Comment by albesp77** [comment] 2017-11-23 16:30
i don't have anymore the iso to test, but anyway vidcoder give me error on finish scan and i have an totally empty title list, so i cannot select anything to convert! instead handbrake i don't remember if give error on finish scan, but all title set are present and i'm able to convert them all without problems!

**Comment by RandomEngy** [comment] 2017-11-25 03:40
I looked at the code and I found your error could happen if the "feature" title indicated by HandBrake was not in the title list due to scan issues. From the log it looks like a couple titles had scan issues, so maybe that's what you ran into. I'll fix this in the next version.

**Comment by RandomEngy** [comment] 2017-11-26 20:01
Fixed in 3.2 Beta.

**Closed by RandomEngy** 2017-11-26 20:01 UTC
