### ISSUE TITLE
Double dialog/crash when loading new preset and not saving changes

### ISSUE THREAD

**Issue by kphipps** [RandomEngy/VidCoder#307] opened 2018-01-19 13:56 UTC
In VidCoder 3.7 Beta, when switching to another preset, and changes have been made to the current one, two copies of the 'save current preset' dialog pop up, and when clicking 'No' on both of them, VidCoder will throw an error dialog: Assertion Failed - 'Error reverting preset: Original profile cannot be null'.

**Comment by RandomEngy** [comment] 2018-01-19 15:34
Thanks for the report, though I'm having difficulty reproducing that one. Can you get your app in a state where the issue is about to happen, then send %appdata%\VidCoder-Beta\VidCoder.sqlite to me?

**Comment by RandomEngy** [comment] 2018-03-12 14:28
Thanks for the report. Fixed in 3.10 Beta.

**Closed by RandomEngy** 2018-03-12 14:28 UTC
