### ISSUE TITLE
Failure to initialise thread 'H.264/AVC encoder (libx264)'

### ISSUE THREAD

**Issue by surlias** [RandomEngy/VidCoder#135] opened 2016-10-31 14:01 UTC
After updating to the 2.35 beta version, any new files that I add to the queue fail. The error I'm seeing in the log file is:

`encx264: x264_encoder_open failed.`
`Failure to initialise thread 'H.264/AVC encoder (libx264)'`

This only seems to happen if I use a preset with anamorphic scaling disabled, which I usually do because I prefer a 1:1 SAR.

The really weird thing is, I still have items in the queue that were added before I updated to 2.35 that are using presets that have anamorphic scaling disabled, and they are still encoding just fine (and producing output with 1:1 SAR). However, if I try to edit one and add it back (without making any changes to the preset), it will fail.

This issue is happening on two different PCs. I've tried uninstalling and reinstalling. I haven't tried uninstalling and with the "remove all personal settings" option yet, and I'd really like to avoid that if possible, because I have tons of presets I don't want to have to export and re-import.

**Comment by RandomEngy** [comment] 2016-10-31 14:41
Can you export your preset and share it? Also do the built-in presets with Anamorphic disabled have the same problem?

**Comment by surlias** [comment] 2016-10-31 15:56
Yes, it happens with the default presets as well as my custom presets. I just tried High Profile with anamorphic disabled, first without saving the changes, and then a second time after saving the changes (which creates a new preset since you can't save changes to the default presets).

I've attached one of my custom presets, as requested.
[boondocks.vjpreset.txt](https://github.com/RandomEngy/VidCoder/files/562218/boondocks.vjpreset.txt)

**Comment by surlias** [comment] 2016-10-31 18:26
Here's an export of the High Profile default preset where the only changes I made were unchecking the box for "Use Anamorphic" and then saved it. This preset exhibits the issue as well.
[High Profile.Anamorphic.Disabled.vjpreset.txt](https://github.com/RandomEngy/VidCoder/files/562541/High.Profile.Anamorphic.Disabled.vjpreset.txt)

**Comment by RandomEngy** [comment] 2016-11-02 05:40
Hmm, can't reproduce the issue on my end with that preset. Does it happen with the latest HandBrake nightly?

**Comment by surlias** [comment] 2016-11-05 14:57
Ok so I think I've narrowed it down a bit. This only seems to be an issue with video stored with a PAR of 1.19 (or possible just a PAR > 1). I've attached a couple 10s samples of raw MPEG2 video that you can test with, one that's PAR 0.89 and one that's PAR 1.19.

I've also included the presets I used to recreate the issue. Both are just the default Normal preset, one with Anamorphic enabled and the other with it disabled, but no other changes. The log files from each are attached as well.

The enabled preset works for both. However, the disabled preset fails on the PAR 1.19 video, but succeeds on the PAR 0.89 video.

[Sample Videos, Presets, Logs.zip](https://github.com/RandomEngy/VidCoder/files/573270/Sample.Videos.Presets.Logs.zip)

**Comment by surlias** [comment] 2016-11-05 15:10
Ok, so in regards to whether all video with PAR > 1 is affected, I've just tested with some PAL content at PAR 1.07 and it didn't present any problems. Attached you'll find a sample and the logs:

[PAR 1.07.zip](https://github.com/RandomEngy/VidCoder/files/573285/PAR.1.07.zip)

**Comment by surlias** [comment] 2016-11-05 15:13
And here's another sample of PAR 1.19 content that fails, just to prove it's not a particular video that's problematic.

[FILM PAR 1.19.zip](https://github.com/RandomEngy/VidCoder/files/573288/FILM.PAR.1.19.zip)

**Comment by RandomEngy** [comment] 2016-11-05 15:35
Thanks for the sample files! I've found the problem and it will be fixed in the next Beta.

**Comment by RandomEngy** [comment] 2016-11-06 05:13
Fixed in 2.36 Beta.

**Closed by RandomEngy** 2016-11-06 05:13 UTC
