### ISSUE TITLE
Unexplained crash - no reason given - error report below

### ISSUE THREAD

**Issue by kaufmanj1973** [RandomEngy/VidCoder#909] opened 2021-10-23 23:18 UTC
Vidcoder successfully converted all files in queue.  When I attempted to right-click and clear the list of successfully completed titles, Vidcoder crashed and provided the error report below.

System.IO.FileNotFoundException: Could not load file or assembly 'Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Windows.Controls.Primitives.Popup.PopupSecurityHelper.ForceMsaaToUiaBridge(PopupRoot popupRoot)
   at System.Windows.Controls.Primitives.Popup.CreateWindow(Boolean asyncCall)
   at System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Data.BindingOperations.SetBinding(DependencyObject target, DependencyProperty dp, BindingBase binding)
   at System.Windows.Controls.Primitives.Popup.CreateRootPopupInternal(Popup popup, UIElement child, Boolean bindTreatMousePlacementAsBottomProperty)
   at System.Windows.Controls.ContextMenu.HookupParentPopup()
   at System.Windows.Controls.ContextMenu.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.PopupControlService.RaiseContextMenuOpeningEvent(IInputElement source, Double x, Double y, Boolean userInitiated)
   at System.Windows.Controls.PopupControlService.ProcessMouseUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.Controls.PopupControlService.OnPostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment] 2021-10-30 18:43
Are you using the installer or the portable version?

**Comment by kaufmanj1973** [comment] 2021-10-31 03:38
This was installed using the standard installer.  (Since then, it's been
upgraded using the automatic upgrade process.)  I've never used the
portable version.

**Comment by RandomEngy** [comment] 2021-10-31 04:42
Thanks. Does this happen every time you try to right click on the completed queue item?

**Comment by RandomEngy** [comment] 2021-10-31 04:57
Also, do you have the Desktop runtime installed? Win + X, F, search "runtime"

![image](https://user-images.githubusercontent.com/9450861/139568471-34b52818-3307-47fa-b910-9fcd9d6d3a24.png)

**Comment by kaufmanj1973** [comment] 2021-10-31 05:19
No, it's random.  Sometimes VidCoder works properly, deleting the original
file that has successfully completed converting.  Sometimes it clears the
completed queue but does *not* delete the original file.  And sometimes I
get the crashing that is the subject of this e-mail.

**Comment by kaufmanj1973** [comment] 2021-10-31 05:21
[image: 2021-10-31 00_20_05-Settings.png]

**Comment by RandomEngy** [comment] 2021-10-31 05:25
Did you try to post a screenshot? It didn't come through, can you try posting directly from the GitHub site?

**Comment by kaufmanj1973** [comment] 2021-10-31 05:32
The screenshot was just the list of runtime versions installed on my
computer.  I have iSEEK AnswerWorks English Runtime 010.000.0101; Microsoft
Edge WebView2 Runtime 95.0.1020.40; and Microsoft Windows Desktop Runtime -
5.0.11 (x64) 5.0.11.30524.

**Comment by RandomEngy** [comment] 2021-10-31 22:21
Thanks. I'm a bit stumped on this one. My app is marked to use the .NET 5 framework, so it should be loading the v5 accessibility DLL. But it's trying to load the v4 version. This is part of the standard .NET SDK and I'm not doing anything special.  Also, a DLL load failing intermittently is really odd. Maybe try uninstalling and re-installing the Microsoft Windows Desktop Runtime?

**Comment by RandomEngy** [comment] 2023-06-14 04:57
Duplicate of #1093

**Closed by RandomEngy** 2023-06-14 04:57 UTC
Labels: bug
