### ISSUE TITLE
Folder watch does not wait for SABnzb direct unpack to complete

### ISSUE THREAD

**Issue by snottyone** [RandomEngy/VidCoder#1095] opened 2023-01-01 10:17 UTC
### Problem Description

VidCoder folder watch does not play nice with the direct unpack feature of SabNZB.
it starts encoding the folders when they are still being written and have `_UNPACK_` in their folder name.

edit: it also hits normal unpacks while they happen, resulting in a Folder Watch "Planned" job that has the UNPACK folder, and no job for the completed unpacked new folder

### What version of VidCoder are you running?

8.14 Beta SquirrelInstaller

**Comment by RandomEngy** [comment] 2023-01-02 21:19
What's the exact sequence of unpacking here? It gets written into to a subfolder named _UNPACK_, then is moved to the final location?

Maybe the output file from the first in-progress unpack is interfering with the encode triggered from the rename.

There's probably something that could be added to help this. Perhaps a regex as part of the Watcher configuration that could be run to ignore certain file paths?

It's something that would have to be added for the v9 Beta as v8 translations are already locked.

**Comment by snottyone** [comment] 2023-01-03 01:31
watcher gets it wrong in both cases of unpacking by sabnzb.

a) sabnzb starts writing the file into a subfolder (of the watched folder) marked with `_UNPACK_` at the start of the folder name while downloading it (direct unpack), moving it to a folder without UNPACK after download is finished

b) sabnzb unpacks the file to a subfolder of the (watched) download folder after it is finished downloading (also with an `_UNPACK_` in folder name at first, then file gets moved to final destination folder without the unpack in the folder name.)
in both cases, watcher does not realize the file is unfinished when it starts encoding.

note:
the files are downloaded and unpacked by a different PC from the one running vidcoder.
the output files go to a third pc, so are not in play.
the rename does NOT trigger another encode, watcher only attempts encoding once and deems it a success.
retry doesn't work because the source folder doesn't exist any more

an exclusion regex would totally be worth a try.

**Comment by snottyone** [comment] 2023-01-17 09:21
with 8.21:
watcher now "sees" new files being added to the watched folder, but not new a folder with a file inside.

it only scans the folder(s) when i either disable/enable watcher, or open a watched folder's setting and close it again without changing anything,

**Comment by RandomEngy** [comment] 2023-01-17 17:14
For that latest problem can you provide the Watcher.txt log file?

**Comment by snottyone** [comment] 2023-01-17 22:59
[2023-01-17 09.52.57 Watcher.txt](https://github.com/RandomEngy/VidCoder/files/10439953/2023-01-17.09.52.57.Watcher.txt)

today, with 8.21, i had one file (not in a folder) be detected by watcher, but it stayed there as 'planned'
several other new files had arrived by then, so i disabled/reenabled watcher, the planned file and the others were then encoded.

in the log, watcher sees new folders written by SABnzb , but if i copy or move a folder to a watched folder, that only gets recognized after disable/reenable

**Comment by snottyone** [comment] 2023-01-27 12:23
summary: move a FILE to watched folder, works perfectly. move a FOLDER to watched folder, nothing happens until you either
* disable/re-enable watcher altogether, or you
* click the settings for a watched folder and close the settings again without change.

both prompt a search of the folder that finds subfolders and encoding starts

**Comment by RandomEngy** [comment] 2023-01-27 18:55
Thanks for the log. I can't reproduce your issue with it not detecting a folder with a file inside though. Could you try to do a clean test of that? Disable/re-enable the file watcher to get a new log started, copy a folder into a watched folder, then send the log to me if it's stuck, along with the expected file names? It would make it easier to isolate the issue.

**Comment by snottyone** [comment] 2023-01-30 17:28
[2023-01-30 18.06.28 Watcher_comments.txt](https://github.com/RandomEngy/VidCoder/files/10538321/2023-01-30.18.06.28.Watcher_comments.txt)
i wrote what i did into the log at the appropriate times.
first one went as it should, subsequent ones get detected but not enqueued.

**Comment by RandomEngy** [comment] 2023-01-30 17:42
Ahh I see, for you it sends events for the created folders but not for the individual files. When you disable and re-enable it runs some other code path that checks every file inside the watched directories. I may be able to create a workaround for that.

What version of Windows are you using?

**Comment by RandomEngy** [comment] 2023-01-30 17:52
Actually nevermind, it appears the file watcher behaves differently for folder copies and folder moves. I can reproduce on my end now. I'll see what I can do here.

**Comment by RandomEngy** [comment] 2023-01-31 21:56
Okay, this should be fixed in 8.24. Thanks for all those detailed error reports.

Let me know if you are still having problems with SABnzb and need the ability to ignore specific subfolders.

**Comment by snottyone** [comment] 2023-02-01 16:52
[2023-02-01 17.26.53 Watcher.txt](https://github.com/RandomEngy/VidCoder/files/10559325/2023-02-01.17.26.53.Watcher.txt)

8.24 solved the "moved folder not recognized" thing, thank you very much!

as to the original bug topic, i added the SABnzb folder again for testing, and 'locked' files still get added to the queue.
S:\#Recode\_UNPACK_etc.  (see log)

probably not fixable, since the files/folders are not locked by the computer running VidCoder, but by the synology (S:) that runs SABnzbd, and i have a workaround anyway, which now works perfectly thanks to your various fixes.

please feel free to close this if either ~the above is a correct assessment, or ~it just isn't worth the bother to fix.
in any case, thanks again for your help so far!

**Comment by RandomEngy** [comment] 2023-02-01 16:56
Great to hear! Since you have a workaround for the SABnzbd issue I'll close the issue.

**Closed by RandomEngy** 2023-02-01 16:56 UTC
Labels: bug
