### ISSUE TITLE
Bugfix requested for v6.32:  Empty duplicate entry still occurs in BATCH QUEUE mode only.

### ISSUE THREAD

**Issue by quebecman** [RandomEngy/VidCoder#830] opened 2021-05-02 03:13 UTC
Hello,

  Yes the popup occurs but it creates BLANK ENTRIES.  More likely, there is something strange behavior.  In the picker, there is missing the CANCEL and ASK option for batch only.

Still, why does a popup OCCURS since a default option is selected in the WHEN FILE ALREADY EXIST do?  Ask, Overwrite, Auto-rename (missing ASK and CANCEL)

![image](https://user-images.githubusercontent.com/4656308/116800893-02661d00-aad3-11eb-8702-db25410b0f26.png)

Thanx.
Regards.

**Comment by RandomEngy** [comment] 2021-05-02 03:34
Who's Mark?

Can you give me a specific set of steps to produce the "empty" result?

I don't understand your question about the dialog.

**Comment by quebecman** [comment] 2021-05-02 03:36
Nevermind for mark... getting really late and I am tired.

![image](https://user-images.githubusercontent.com/4656308/116801249-047dab00-aad6-11eb-83de-d9929a68994b.png)

**Comment by RandomEngy** [comment] 2021-05-02 03:38
Okay I can reproduce now. I don't want to add the "Ask" option to the batch mode because it could result in hundreds of sequential dialog boxes.

**Comment by quebecman** [comment] 2021-05-02 03:39
Well, at least the CANCEL option and NO popup if one of the 3 options are selected.

**Comment by RandomEngy** [comment] 2021-05-02 03:47
The blank item on cancel issue will be fixed in the next Beta release.

**Comment by quebecman** [comment] 2021-05-02 03:49
What about the behavior.  Do you think this will be remove and replaced by the POPUP because now, you have the POPUP and the option in the PICKER.

  It's too late for me... Going to sleep... keep up the excellent work.

**Comment by RandomEngy** [comment] 2021-05-02 04:01
Fixed in 6.33 Beta.

**Closed by RandomEngy** 2021-05-02 04:01 UTC
