### ISSUE TITLE
pickers in watcher get file deletions wrong

### ISSUE THREAD

**Issue by snottyone** [RandomEngy/VidCoder#1144] opened 2023-06-06 20:26 UTC
### Problem Description

i have several pickers in use in the watcher.
i enabled file deletion upon job completion in ONE of them.
worked when i only tested files with the picker where deletion is enabled.
now the OTHER pickers deletes files, the one set to delete doesn't.

in log, ALL the AR episodes at the top should have been deleted, the one at the bottom should not have been.
[2023-06-06 12.09.22 General.txt](https://github.com/RandomEngy/VidCoder/files/11668792/2023-06-06.12.09.22.General.txt)

### What version of VidCoder are you running?

8.25 SquirrelInstaller

**Comment by RandomEngy** [comment] 2023-06-10 06:37
Thanks for the report. I think the root cause here is that this logic is working based on the currently selected picker, and not the picker that originally queued the item.

This is fixed in 9.8 Beta.

**Closed by RandomEngy** 2023-06-10 06:37 UTC
Labels: bug
