### ISSUE TITLE
[REQUEST] Multiple

### ISSUE THREAD

**Issue by refriedfood** [RandomEngy/VidCoder#354] opened 2018-07-17 06:58 UTC
Disable standby / screensaver option

No, I do not want to be asked _every_ time: "Would you like to apply your new changes to every queued encode in the list?" Of course I don't -- Give me a no-nag option.

Thank you.

**Comment by RandomEngy** [comment] 2018-07-17 15:49
VidCoder is already set up to prevent the system from going to sleep while it's encoding. Did you also want an option to prevent the display from turning off? Are you checking the encode progress while doing other things or something?

As for that prompt, I'll look into adding a "don't remind me" option there.

**Comment by refriedfood** [comment] 2018-09-17 10:40
3.15 x64 does not stop your screensaver from starting. I tested it multiple times. This is on win 7 x64.

I also want to add that there was an option that has been removed, which I quite enjoyed, to edit your enqueued items, and when you did so, the settings would be returned to what the queued item was set in. This is no longer featured and I'm not sure why. Now if I need to edit, I have to start all over or make a pre-save profile for each encode I plan to do. This is bothersome.

**Comment by RandomEngy** [comment] 2018-09-17 16:41
Yes, I know it doesn't stop the screensaver from starting. I was asking why you wanted it to do so, so I could know the motivation behind the feature request.

Also I did not remove the edit queue item option. Can you attach a screenshot of context menu when you right click a queue item?

**Comment by refriedfood** [comment] 2018-09-17 23:11
@RandomEngy 
A screensaver takes up cpu power away from the worker/encoder. I'm just saying an option to disable while working would be nice.

The "edit" button is there, what is no longer there is saving it as its own preset "Restored from Queue". Instead it overwrites your own preset if you select to save the preset upon editing, or it reverts to the original preset if you select no (forcing you to start over).

Example: https://weshare.me/d26ec1c3fb3fe2a2/20180917_1601_49.mkv

I hope this clears up the confusion.

**Comment by RandomEngy** [comment] 2018-09-18 13:50
Why do you use a screensaver rather than just having it set to turn off the display?

About "Restored from Queue" - Ahh, I see what you mean now. This will be fixed in the next Beta release.

**Comment by refriedfood** [comment] 2018-09-18 23:17
Personally? my screensaver kicks ass, that's why. It's an aquarium which lights up the room. But, even when I turn off the display and encode over night, the screensaver will still come on regardless of which you use. It's an OS thing. I don't think it's a real big issue as I have no way of knowing if it would shave off rendering time at all. That's why I figured if there were an option there to have the screensaver disabled when encoding it would might help - like some programs have the option to prevent your hdd going into standby, etc.

**Comment by RandomEngy** [comment] 2018-09-23 15:52
Fixed the "restored from queue" functionality in 4.14 Beta.

**Comment by refriedfood** [comment] 2018-09-23 22:18
Fantastic, I'll be sure to try it out.

**Comment by RandomEngy** [comment] 2018-10-31 07:08
I removed the "would you like to apply your changes" dialog in 4.19 Beta. Applying changes to the queue now happens with a button press.

**Closed by RandomEngy** 2018-10-31 07:08 UTC

**Comment by RandomEngy** [comment] 2018-10-31 07:10
Please open a new item to track your "keep display on" request.

**Comment by refriedfood** [comment] 2018-11-02 21:20
No that's fine. I realize now that it's actually a different problem. Your past versions didn't do this, but apparently when using 3.15 and selecting to shutdown after finished, it doesn't shutdown (or only do periodically) if you have more than 3 encode jobs. It just locks up my comp. Whereas the older version does not. I'm not sure if this is an x264 155 issue or if it's the program - only you would know that. In the meantime I'm going to test the beta, I'll give feedback on it, but for all my serious encodes I had to go back pre-3.15.

so far, the beta looks nice, you fixed the audio bitrate detection problem, not too keen on the new top buttons (I prefer minimal over bubbly big), only thing I could see right off the bat is there is no export all custom presets. It's still 1 by 1. Keep up the good work!

**Comment by RandomEngy** [comment] 2018-11-03 20:17
Does it only fail to shutdown if the screensaver has come on? If you make 3 small encodes that finish before the screensaver comes on, does it work?

And what does your computer do when it "locks" exactly? Is it going to sleep with the fans shut down? Or is it just sitting on the lock screen?

**Comment by refriedfood** [comment] 2018-11-05 09:43
No problem. Here's the whole report it gives if that helps at all.

```
On Fri 11/2/2018 5:23:46 PM GMT your computer crashed
crash dump file: C:\Windows\memory.dmp
uptime: 21:26:36
This was probably caused by the following module: Unknown (0x00000000) 
Bugcheck code: 0x1E (0xFFFFFFFFC0000005, 0x0, 0x8, 0x0)
Error: KMODE_EXCEPTION_NOT_HANDLED
Bug check description: This indicates that a kernel-mode program generated an exception which the error handler did not catch.
This appears to be a typical software driver bug and is not likely to be caused by a hardware problem. 
A third party driver was identified as the probable root cause of this system error. It is suggested you look for an update for the following driver: Unknown . 
```
I'll let you know if the beta version does it.

**Comment by RandomEngy** [comment] 2018-11-05 14:58
Yeah it looks like it was caused by some driver code and not VidCoder.
