### ISSUE TITLE
Target size no longer close

### ISSUE THREAD

**Issue by brettkramer** [RandomEngy/VidCoder#1045] opened 2022-08-18 02:42 UTC
### Problem Description

Hello, I'm using Vidcoder 7.15 on a Windows 8 laptop.  Up until recently, when you used a target file size, for example 10,300, you would end up with a final file size of 10Gb.  However, now, I can type in a target file size of, for example 17,500 and I get a final file size of 11.3Gb.  I'm not sure if I checked a box by mistake and messed things up or there's a bug.  Can anyone offer assistance, maybe tell me what your settings are or provide a screenshot.  Thank you

### What version of VidCoder are you running?

7.15

**Comment by RandomEngy** [comment] 2022-08-19 02:03
Duplicate of https://github.com/RandomEngy/VidCoder/issues/1046

**Closed by RandomEngy** 2022-08-19 02:03 UTC
Labels: bug
