### ISSUE TITLE
VidCoder Will Not Encode Anymore; Only Fails :-(

### ISSUE THREAD

**Issue by tripplesix** [RandomEngy/VidCoder#213] opened 2017-06-21 22:03 UTC
Using VidCoder version 2.53 (x64)
OS: Windows 64-bit

As soon as I solved my previous problem, this problem began.
I think it was two nights ago, after my last encode for the night, I was closing VidCoder when it told me there was an update and asked if I want to install. As usual, I said, yes. It installed and then I shut down my computer.

The next day (yesterday) I tried to continue with my encoding and it failed. I first tried to encode Breakdown; it failed. I then tried to encode Breakin' All the Rules; it failed. I was able to rip Breakdown to my computer (with Any DVD) and then I dropped the file into Vidcoder; it failed. So today, I tried it one more time with the last DVD I was able to encode, Bowling for Columbine; it failed.

It is obviously related to the update. What can I do?

These are the log files of today's failed attempt:
[Bowling for Columbine (2002)-1.mp4 2017-06-21 17.50.18.txt](https://github.com/RandomEngy/VidCoder/files/1093038/Bowling.for.Columbine.2002.-1.mp4.2017-06-21.17.50.18.txt)

**Comment by RandomEngy** [comment] 2017-06-21 22:39
What's the log say when running 2.54?

**Comment by tripplesix** [comment] 2017-06-21 23:23
Just upgraded (again). Failed.
This is the log (different movie):
[Breakdown (1997).mp4 2017-06-21 19.20.24.txt](https://github.com/RandomEngy/VidCoder/files/1093214/Breakdown.1997.mp4.2017-06-21.19.20.24.txt)

How do you downgrade?

**Comment by RandomEngy** [comment] 2017-06-22 00:00
You should be able to run the installer from 2.52: https://github.com/RandomEngy/VidCoder/releases/tag/v2.52 . If you uninstall the current version make sure you select the option to keep all your user files.

**Comment by tripplesix** [comment] 2017-06-22 00:30
Does "keep all my user files" mean it will save **all** my settings for sure?

**Comment by tripplesix** [comment] 2017-06-22 00:31
Also, do you know why it is suddenly not working (with 2 upgrades)?

**Comment by RandomEngy** [comment] 2017-06-22 05:23
Okay try 2.55, I was able to get a repro so I *think* it's really fixed now. But yes, it does keep all your settings. And it broke because I made a relatively complex fix to another bug, and it caused this regression.

If everything isn't back to normal, let me know.

**Closed** 2017-06-22 05:42 UTC

**Comment by tripplesix** [comment] 2017-06-22 22:40
Yaaaaassss.
You. You are that dude.
I am back in business!
Thanks so much for fixing that and having this help site/section and responding so quickly and so forth and so on!
